### PR TITLE
GPU howto: cuBLAS and NVBLAS configuration

### PR DESCRIPTION
**Pull request by avulanov**
Added a section to `README.md` called "GPU" that describes how to use NVBLAS within netlib-java.

### CODE REVIEW

**Comment by fommil** [comment]
awesome, thanks! I'm sure many people will be thankful of this.

I think it's a bit long and detailed for the README --- it's actually longer the entire current section on system optimised natives. I'd be happy to take this as a full Wiki page. Do you have edit rights to create a new page?

Then we'll create a link to the wiki page. Hopefully, being a wiki, others will feel compelled to expand on it and we're more likely to have up-to-date instructions. :smile:

**Comment by avulanov** [comment]
You are welcome! 

I was able to create a wiki page (actually the first one in the project(?)), but didn't try to save it. Should we leave the main bullets in the readme and put the rest to the wiki? The other option would be to reduce the amount of text and don't bother creating wiki.

**Comment by fommil** [comment]
save it, for sure! The Wiki is a great place for documenting exotic natives. Probably best that you call it NVBLAS rather than something generic like GPU.

**Comment by fommil** [comment]
@avulanov 

```
You also need a library that has CBLAS interface and calls Fortran BLAS. In Debian/Ubuntu it is libblas.so.3:
```

In Debian/Ubuntu the `libblas.so.3` **is** the Fortran and C API together. Are you sure that this technique works?

Given that we have to compile CBLAS anyway, it feels like a simpler approach might be to compile the netlib CBLAS API with linking flags to `nvblas.so`. Then there should be no need to LD_PRELOAD anything and users on Debian-based systems can simply use the alternatives system.

Indeed, since the compilation of the CBLAS API, linked to NVBLAS, is MIT licensed, you/we could even offer a `.tar.gz` download to go into `/opt/nvblas`.

**Comment by avulanov** [comment]
Yes, it does. It works because CBLAS functions call BLAS Fortran functions. The latter are replaced with preloaded symbols in runtime. CBLAS shared library that I compiled for Fedora also contains Fortran BLAS.

I am not sure how linking with nvblas.so will work because it has only a number of Fortran BLAS level 3 symbols, not all of the BLAS.

**Comment by fommil** [comment]
ok, I didn't realise that it was possible to have multiple definitions of the same symbols in C. How come this doesn't work for ATLAS?

I'll add the link tonight, ping me if I forget.

**Comment by avulanov** [comment]
As far as I understood, It does not work for ATLAS (or OpenBLAS) because its C functions do not call Fortran BLAS, they call their own routines instead.

**Comment by fommil** [comment]
I'm pretty sure ATLAS and OpenBLAS implement both the fortran and C APIs. You can check by inspecting the binaries, the fortran API just gets an underscore before its name in C land.

**Comment by fommil** [comment]
linked :smile: thanks again! And don't forget to post the link to the spark mailing list

**Comment by avulanov** [comment]
You are correct, ATLAS and OpenBLAS do implement Fortran and C APIs and they do have those symbols, otherwise they could not tell that they are BLAS :) However, that does not mean that their C API calls their Fortran API, what is needed for plugging nvblas.

**Comment by fommil** [comment]
got you now

**Pull request closed without merging**
